language: python
python:
  - "3.5"
install: "pip install -r requirements.txt"
script: ./run_tests.sh
addons:
    code_climate:
        repo_token: 8b49dedca5bcdaf03eb2cbafd04c45e2536ca2faf9f4506844b0b6cdaf14fc83
